using UnityEngine;
using System.Collections;

public enum Episode
{
	NONE,
	INTRO_VIDEO,
	ORIENTATION,
	TERRYS_APARTMENT,
	NEWAAR1,
	ORIENTATION2,
	THUNDERJAW,
	NEWAAR2,
	ORIENTATION3,
	WAREHOUSE,
	NEWAAR3,
	CONCLUSION
}

public enum Sex
{
	MALE,
	FEMALE,
	UNSPECIFIED
}

public enum AARSlideType
{
	Movie,
	Basic,
	BasicImage,
	QuizSliderImage,
	QuizRadiosImage,
	QuizSlider,
	QuizRadios,
	Spinner
}

public enum Narrator
{
	Generic,
	Anchoring,
	Represenative,
	Projection,
	SME,
	SME2,
	Computer
}

public enum Quiz
{
	NONE,
	GAME_1_2_AVERAGE_FACEBOOK_USE,
	GAME_1_2A_AVERAGE_FACEBOOK_USE_SLIDER,
	GAME_1_4_FLAHERTY_RACKETEERING,
	GAME_1_5_GYM,
	GAME_1_6_PARKS,
	GAME_1_6A_PARKS_SLIDER,
	GAME_2_1A_STOCK_PRICE,
	GAME_2_4_NYC_POPULATION,
	GAME_2_4B_MARLIN_LENGTH,
	GAME_2_HUNTING_ME,
	GAME_2_HUNTING_THEM,
	GAME_3_3_PALLET_COUNT,
	GAME_3_4_AMMO_COUNT,
	GAME_3_8_TRAVIS_TRIAL,
	AAR1_CATAMARAN,
	AAR1_CATAMARAN_SLIDER,
	AAR1_PLAYING_CARDS,
	AAR1_PLAYING_CARDS_SLIDER,
	AAR1_WIMBLEDON,
	AAR1_MAYOR_FLEESE,
	AAR1_SODAS,
	AAR1_SODAS_SLIDER,
	AAR1_GLOBAL_WARMING,
	AAR1_GLOBAL_WARMING_SLIDER,
	AAR1_SATANIST,
	AAR1_OUTGOING_INDIAN,
	AAR2_CAR_COLORS,
	AAR2_BABY_PREDICTION,
	AAR2_MAGIC_SCARF,
	AAR2_VIVALDI,
	AAR2_JUDGES,
	AAR3_GOLDILOCKS,
	AAR3_FISHING,
	AAR3_AIRPORT,
	AAR2_SOLAR_ME,
	AAR2_SOLAR_THEM,
	AAR2_SOLAR_DIFF,
	GAME_2_HUNTING_DIFF
}

public enum QuizType
{
	TrueFalse,
	MultipleChoice,
	Slider
}
